-- print("auto-dark-mode config")
-- require('auto-dark-mode').setup({
-- 	update_interval = 1000,
-- 	set_dark_mode = function()
--             vim.o.background = "dark"
--             print("dark mode")
-- 	end,
-- 	set_light_mode = function()
--             vim.o.background = "light"
--             print("light mode")
-- 	end,
-- })
